In [1]:
import numpy as np
from numpy import array, vstack, hstack

# 1. Create a 3x3x3 array with random values

In [2]:
#   OR
a1 = np.random.randn(3,3,3)
print(a1)

[[[-0.70347655 -0.2894718  -1.00296977]
  [-1.25869832 -0.72730781  0.65919142]
  [ 0.79463782  0.97239413 -1.18235557]]

 [[ 1.21496169  1.51109442 -0.11259213]
  [-0.12065371 -1.21559512  0.91631   ]
  [-1.20325294  1.05109928 -0.36111108]]

 [[ 0.32552151 -0.41673457 -1.82639251]
  [ 0.80229056 -0.07840594  1.00616214]
  [ 1.07919056 -0.42518355 -2.51345363]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a2 = np.zeros((5,5))
for i in range(1,5):
    for j in range(i):
        a2[i,j] = j+1
print(a2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 2. 3. 4. 0.]]


In [4]:
a_2 = np.zeros((5,5))
for i in range(1,5):
    a_2[i,i-1] = i
print(a_2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
a3 = np.ones((8,8))
for row in range(len(a3)):
    for column in range(row%2, 8, 2):
        a3[row,column] = 0  
print(a3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [6]:
a4 = np.linalg.norm(a1)
print(a4)

5.36981543836272


# 5. How to find common values between two arrays?

<div style="margin-top: 10px;font-size: 19px;color:#333">
    We can use the numpy method intersect1d() which can find all common values between two arrays<br>
</div>

In [7]:
a5 = np.intersect1d(a3,a2)
print(a5)

[0. 1.]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
today = np.datetime64("today")
yesterday = today - np.timedelta64(1, "D")
tomorrow = today + np.timedelta64(1, "D")
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2020-07-28
Today: 2020-07-29
Tomorrow: 2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [9]:
np.array_equal(a2, a_2)

False

# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
#Keeping in mind there can be more than one element having max value 
vector = np.random.random(10)

print("Initial:",vector,"\n")

print("Max:", max(vector),"\n")

vector = np.where(vector == max(vector), 0, vector)
print("Final:",vector)

Initial: [0.84750259 0.94853519 0.43461037 0.83768766 0.06657432 0.30263156
 0.12539547 0.76996206 0.13770494 0.40019628] 

Max: 0.9485351911969973 

Final: [0.84750259 0.         0.43461037 0.83768766 0.06657432 0.30263156
 0.12539547 0.76996206 0.13770494 0.40019628]


# 9. How to print all the values of an array?

In [11]:
print(a2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 2. 3. 4. 0.]]


# 10.Subtract the mean of each row of a matrix

In [12]:
a10 = a_2-a_2.mean(axis=1)[:,None]
a10

array([[ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.8, -0.2, -0.2, -0.2, -0.2],
       [-0.4,  1.6, -0.4, -0.4, -0.4],
       [-0.6, -0.6,  2.4, -0.6, -0.6],
       [-0.8, -0.8, -0.8,  3.2, -0.8]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [13]:
print(f"Initial: {vector} \n")
vector2 = np.array([0,1,2,1,3,3])
print(f"Indexed vector: {vector2} \n")
for index in np.unique(vector2):
    if index < vector.shape[0]:
        vector[index]+=1
print(f"Final: {vector}")

Initial: [0.84750259 0.         0.43461037 0.83768766 0.06657432 0.30263156
 0.12539547 0.76996206 0.13770494 0.40019628] 

Indexed vector: [0 1 2 1 3 3] 

Final: [1.84750259 1.         1.43461037 1.83768766 0.06657432 0.30263156
 0.12539547 0.76996206 0.13770494 0.40019628]


# 12.How to get the diagonal of a dot product?

In [14]:
a = np.array([[0,1,2],[3,4,5]])
print(f"a:\n{a}\n")
b = a.T
print(f"b:\n{b}\n")
a12 = np.diag(a.dot(b))
a12

a:
[[0 1 2]
 [3 4 5]]

b:
[[0 3]
 [1 4]
 [2 5]]



array([ 5, 50])

In [15]:
if a.shape[1] == b.shape[0]:
    for row_a in range(a.shape[0]):
        l = a[row_a, :] * b[:, row_a]
        print(l.sum())

5
50


# 13.How to find the most frequent value in an array?

In [16]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 5 9 0 8 7 8 9 7 4 7 4 6 0 6 9 0 6 9 1 9 6 3 5 0 5 2 3 2 5 4 9 2 2 6 4 4
 0 9 6]
Most frequent value in the above array:
9


# 14.How to get the n largest values of an array

In [17]:
a = np.array([[1,3,1],[4,6,1]])
print("a:\n", a)
n = int(input("Enter n: "))
n *= -1

a:
 [[1 3 1]
 [4 6 1]]
Enter n: 2


In [18]:
np.sort(a.flatten())[n:]

array([4, 6])

# 15.How to create a record array from a regular array?

In [19]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
